# Generated by Django 2.2.2 on 2020-03-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='height_field',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='images/', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='question',
            name='width_field',
            field=models.IntegerField(default=50),
        ),
    ]
